
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jul 11 16:32:28 EST 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 9;
  public static final int CADENA = 18;
  public static final int OR = 10;
  public static final int WRITEINTRO = 13;
  public static final int NOT = 5;
  public static final int ENTONCES = 6;
  public static final int WRITESTR = 11;
  public static final int WRITETABLA = 14;
  public static final int ID = 20;
  public static final int TAUTO = 15;
  public static final int ASIGNACION = 8;
  public static final int DECI = 17;
  public static final int EOF = 0;
  public static final int NUMERO = 19;
  public static final int error = 1;
  public static final int PUNTOCOMA = 2;
  public static final int PARENTIZQ = 3;
  public static final int DOBLEENTONCES = 7;
  public static final int PARENTDER = 4;
  public static final int CONTRA = 16;
  public static final int WRITELOG = 12;
}

